version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - half-suit-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend
    networks:
      - half-suit-network

networks:
  half-suit-network:
    driver: bridge
